
package org.hemologica.service.ws.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.hemologica.service.ws.MovementData;
import org.hemologica.service.ws.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://ws.service.hemologica.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param arg0
     * @throws Exception
     */
    @WebMethod(operationName = "PROVIDE_CDA")
    @RequestWrapper(localName = "PROVIDE_CDA", targetNamespace = "http://ws.service.hemologica.org/", className = "org.hemologica.service.ws.PROVIDECDA")
    @ResponseWrapper(localName = "PROVIDE_CDAResponse", targetNamespace = "http://ws.service.hemologica.org/", className = "org.hemologica.service.ws.PROVIDECDAResponse")
    @Action(input = "http://ws.service.hemologica.org/Service/PROVIDE_CDARequest", output = "http://ws.service.hemologica.org/Service/PROVIDE_CDAResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://ws.service.hemologica.org/Service/PROVIDE_CDA/Fault/Exception")
    })
    public void provideCDA(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception
    ;

    /**
     * 
     * @param arg0
     * @throws ParseException
     */
    @WebMethod(operationName = "IMPORT_MOVEMENTS")
    @RequestWrapper(localName = "IMPORT_MOVEMENTS", targetNamespace = "http://ws.service.hemologica.org/", className = "org.hemologica.service.ws.IMPORTMOVEMENTS")
    @ResponseWrapper(localName = "IMPORT_MOVEMENTSResponse", targetNamespace = "http://ws.service.hemologica.org/", className = "org.hemologica.service.ws.IMPORTMOVEMENTSResponse")
    @Action(input = "http://ws.service.hemologica.org/Service/IMPORT_MOVEMENTSRequest", output = "http://ws.service.hemologica.org/Service/IMPORT_MOVEMENTSResponse", fault = {
        @FaultAction(className = ParseException.class, value = "http://ws.service.hemologica.org/Service/IMPORT_MOVEMENTS/Fault/ParseException")
    })
    public void importMOVEMENTS(
        @WebParam(name = "arg0", targetNamespace = "")
        List<MovementData> arg0)
        throws ParseException
    ;

}
