
package org.hemologica.xds.respository.adapter.repositorioxds;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.hemologica.xds.respository.adapter.ihe.iti.xds_b._2007.RetrieveDocumentSetRequestTypeDocumentRequest;
import org.hemologica.xds.respository.adapter.ihe.iti.xds_b._2007.RetrieveDocumentSetResponseTypeDocumentResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "adocumentrepository", targetNamespace = "RepositorioXDS")
@XmlSeeAlso({
	org.hemologica.xds.respository.adapter.ihe.iti.xds_b._2007.ObjectFactory.class,
	org.hemologica.xds.respository.adapter.oasis.names.tc.ebxml_regrep.xsd.rim._3.ObjectFactory.class,
	org.hemologica.xds.respository.adapter.oasis.names.tc.ebxml_regrep.xsd.rs._3.ObjectFactory.class,
	org.hemologica.xds.respository.adapter.repositorioxds.ObjectFactory.class
})
public interface Adocumentrepository {


    /**
     * 
     * @param retrievedocumentsetrequest
     * @return
     *     returns java.util.List<ihe.iti.xds_b._2007.RetrieveDocumentSetResponseTypeDocumentResponse>
     */
    @WebMethod(operationName = "RETRIEVEDOCUMENTSET")
    @WebResult(name = "Retrievedocumentsetresponse", targetNamespace = "")
    @RequestWrapper(localName = "RETRIEVEDOCUMENTSET", targetNamespace = "RepositorioXDS", className = "repositorioxds.RETRIEVEDOCUMENTSET")
    @ResponseWrapper(localName = "RETRIEVEDOCUMENTSETResponse", targetNamespace = "RepositorioXDS", className = "repositorioxds.RETRIEVEDOCUMENTSETResponse")
    public List<RetrieveDocumentSetResponseTypeDocumentResponse> retrievedocumentset(
        @WebParam(name = "Retrievedocumentsetrequest", targetNamespace = "")
        List<RetrieveDocumentSetRequestTypeDocumentRequest> retrievedocumentsetrequest);

    /**
     * 
     * @param submitobjectsrequest
     * @param documentsrequest
     * @return
     *     returns repositorioxds.RegistryResponseType
     */
    @WebMethod(operationName = "PROVIDEANDREGISTERDOCUMENTSET")
    @WebResult(name = "Registryresponse", targetNamespace = "")
    @RequestWrapper(localName = "PROVIDEANDREGISTERDOCUMENTSET", targetNamespace = "RepositorioXDS", className = "repositorioxds.PROVIDEANDREGISTERDOCUMENTSET")
    @ResponseWrapper(localName = "PROVIDEANDREGISTERDOCUMENTSETResponse", targetNamespace = "RepositorioXDS", className = "repositorioxds.PROVIDEANDREGISTERDOCUMENTSETResponse")
    public RegistryResponseType provideandregisterdocumentset(
        @WebParam(name = "Submitobjectsrequest", targetNamespace = "")
        SubmitObjectsRequest submitobjectsrequest,
        @WebParam(name = "Documentsrequest", targetNamespace = "")
        DocumentsRequest documentsrequest);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PING")
    @WebResult(name = "Pingresult", targetNamespace = "")
    @RequestWrapper(localName = "PING", targetNamespace = "RepositorioXDS", className = "repositorioxds.PING")
    @ResponseWrapper(localName = "PINGResponse", targetNamespace = "RepositorioXDS", className = "repositorioxds.PINGResponse")
    public String ping();

}
